language: java
jdk:
  - oraclejdk8

before_deploy:
    on:
      tags: true


before_script:
    - chmod +x ./script/before_script.sh;
    - ./script/before_script.sh
    #- docker login -e="$DOCKERHUB_EMAIL" -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASSWORD"
    #- chmod +x ./script/bucle_check_url.sh;
    #- docker-compose up & ./script/bucle_check_url.sh;

script:
    - echo "El job de Travis es ${TRAVIS_JOB_NUMBER}";
    - chmod +x ./script/execute-test.sh;
    - ./script/execute-test.sh localhost

addons:
  sauce_connect:
    username: "${SAUCELABS_USER}"
    access_key: "${SAUCELABS_ACCESS_KEY}"

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1
  
before_install:
  - chmod +x ./script/before_install.sh;
  - ./script/before_install.sh
  #- sudo rm /usr/local/bin/docker-compose
  #- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  #- chmod +x docker-compose
  #- sudo mv docker-compose /usr/local/bin

