language: java
jdk:
  - oraclejdk8

before_deploy:
    on:
      tags: true


#before_script:
   # - chmod +x ./script/before_script.sh
   # - ./script/before_script.sh;

before_install:
  - chmod +x ./script/before_install.sh;
  - ./script/before_install.sh

script:
    - echo "El job de Travis es ${TRAVIS_JOB_NUMBER}";
    - chmod +x ./script/execute-test.sh;
    - ./script/execute-test.sh localhost

#addons:
#  sauce_connect:
#    username: "${SAUCELABS_USER}"
#    access_key: "${SAUCELABS_ACCESS_KEY}"

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2
  #DOCKER_COMPOSE_VERSION: 1.8.1
 
