language: java
jdk:
  - oraclejdk8

before_deploy:
    on:
      tags: true


before_script:
    - docker login -e="$DOCKERHUB_EMAIL" -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASSWORD"
   # - docker pull grupoasv/mule:latest;
    - chmod +x ./script/bucle_check_url.sh;
    - docker-compose up & ./script/bucle_check_url.sh;
    - ifconfig;

script:
    - CONTAINER_ID=`docker ps -a | grep grupoasv | awk '{print $1 }'`
    - CONTAINER_NETWORK_MODE=`docker inspect --format '{{ .HostConfig.NetworkMode }}' ${CONTAINER_ID}`
    - CONTAINER_IP_TXT="{{ .NetworkSettings.Networks.${CONTAINER_NETWORK_MODE}.IPAddress }}"
    - CONTAINER_IP=`docker inspect --format "${CONTAINER_IP_TXT}" ${CONTAINER_ID}`
    - echo "La IP del contenedor ${CONTAINER_ID} (contenedor de ${CONTAINER_NETWORK_MODE}) es ${CONTAINER_IP}"
    - ETH0_IP=`ifconfig | grep -A1 'eth0' | grep 'inet addr:' | cut -d":" -f2 | awk '{ print $1 }'`
    - echo "La IP de eth0 es ${ETH0_IP}"
    - curl --trace-ascii - http://${CONTAINER_IP}:8088/extranet-ssff
    - curl --trace-ascii - http://${ETH0_IP}:8088/extranet-ssff
    - curl --trace-ascii - http://127.0.0.1:8088/extranet-ssff
    - curl --trace-ascii - http://127.0.0.1/
    - chmod +x ./script/execute-test.sh;
#    - ./script/execute-test.sh

#after_success:
#  - echo "${TRAVIS_TAG}"
#  - if [[ "${TRAVIS_TAG}" =~ (.*)-TESTME ]]; then mvn test; fi

addons:
  sauce_connect:
    username: "travis-arq-testing1"
    access_key: "0c5a2380-863d-45c7-b6d0-2c55d6d93ba1"
    #access_key: "dfcd0c77-25c6-42ba-92f3-d85e08bb036c"
    #username: "Your Sauce Labs access key"
    #access_key: "Your Sauce Labs access key"

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1
  
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  #- cd /usr/local/bin
  #- ls -la
